version: 2.1
orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@1.5.0 
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  # pre-build:
  #   executor: python/default
  #   steps:
  #     - checkout
  #     - python/install-packages:
  #         pkg-manager: pip      
  build:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-packages-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: |
            sudo npm install -g npm@8.3.2
            sudo npm install angular-cli@latest -g
      - save_cache:
          name: Save Package Cache
          key: npm-packages-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules/
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run api:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run api:build
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Unit Test
          command: |
            npm run test
      # - run:
      #     name: End to End Test
      #     command: npm run e2e
  deploy:
    executor: node/default
    steps:
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
            npm run api:deploy
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold