version: 2.1
orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@1.5.0 
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
  browser: circleci/browser-tools@1.2.4
jobs:
  pre-build:
    executor: python/default
    steps:
      - python/install-packages:
          pkg-manager: pip             
  build: 
    executor: node/default
    steps:
      - node/install:
          node-version: '16.13.1'
      - aws-cli/setup
      - eb/setup
      - browser/install-chrome  
      - checkout
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-packages-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: |
            npm install -g npm@8.3.2
            npm install angular-cli@latest -g
      - save_cache:
          name: Save Package Cache
          key: npm-packages-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules/
      - run:           
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run api:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run api:build
  test: 
    executor: node/default
    steps:
      - checkout
      - run:
          name: Unit Test
          command: |
            npm run test
  deploy: 
    executor: node/default
    steps:
      - checkout
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
            npm run api:deploy
workflows:
  Deploy:
    jobs:
      - pre-build
      - build:
          requires:
            - pre-build
      - test:
          requires:
            - build
      - deploy:    
          requires:
            - build
            - test