version: 2.1
orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@1.5.0 
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
  browser: circleci/browser-tools@1.2.4
jobs:
  build: 
    executor: node/default
    steps:
      - node/install:
          node-version: '16.13.1'
      - checkout
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-packages-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: |
            npm install -g npm@8.3.2
      - save_cache:
          name: Save Package Cache
          key: npm-packages-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules/
      - browser/install-chrome
      - aws-cli/setup
      - eb/setup

      # Install and build applcatoin (API and Frontend)
          # Install dependencies of Frontend  and API
      - run:           
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run api:install

          # Build Both Frontend and API
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run api:build
      
      # Test Application      
      - run:
          name: Unit Test
          command: |
            npm run test

      # Deploy Application
          # API to Elastic Beanstalk and 
          # Frontend to S3 
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
            npm run api:deploy 

workflows:
  main:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master